# ------------------------------------------------------------
# openapi/openapi.yaml
# ------------------------------------------------------------
openapi: 3.0.2
info:
  version:        1.0.0
  title:          taxi.com
  description:    Example rideshare API
path:
  /passengers:
    $ref: './paths/passengers/passengers.openapi.yaml'
  /drivers:
    $ref: './paths/drivers/drivers.openapi.yaml'
  /payments:
    $ref: './paths/payments/payments.openapi.yaml'

